import {
    AiOutlineUser,
    AiOutlineShopping,
    AiOutlineFileAdd,
    AiOutlineUnorderedList,
    AiOutlineRead,
    AiOutlineLock,
} from "react-icons/ai";
import { BsClipboard } from "react-icons/bs";
import learnerSVG from "../assets/images/Home/customer_learner.svg";
import parentsSVG from "../assets/images/Home/customer_parents.svg";
import teacherSVG from "../assets/images/Home/customer_teacher.svg";

export const mobileWidth = 767;

export const desktopWidth = 1023;

export const userMenuData = [
    { _id: 0, name: "Dashboard", link: "user", icon: BsClipboard },
    { _id: 1, name: "Profile", link: "user/profile", icon: AiOutlineUser },
    {
        _id: 2,
        name: "Change Password",
        link: "user/profile/password",
        icon: AiOutlineLock,
    },
    { _id: 3, name: "My Order", link: "user/orders", icon: AiOutlineShopping },
];

export const adminMenuData = [
    { _id: 0, name: "Dashboard", link: "admin", icon: BsClipboard },
    {
        _id: 1,
        name: "Product level category",
        link: "admin/category",
        icon: AiOutlineRead,
    },
    {
        _id: 2,
        name: "Product age category",
        link: "admin/ageCategory",
        icon: AiOutlineRead,
    },
    {
        _id: 3,
        name: "Create a new product",
        link: "admin/product",
        icon: AiOutlineFileAdd,
    },
    {
        _id: 4,
        name: "View products",
        link: "admin/products",
        icon: AiOutlineUnorderedList,
    },
    {
        _id: 5,
        name: "Blog category",
        link: "admin/blog/category",
        icon: AiOutlineRead,
    },
    {
        _id: 6,
        name: "Create a blog post",
        link: "admin/blog/createpost",
        icon: AiOutlineFileAdd,
    },
    {
        _id: 7,
        name: "View blog posts",
        link: "admin/blog/list",
        icon: AiOutlineUnorderedList,
    },
];

export const worksheetTextData = [
    {
        _id: 1,
        title: "Fun subjects",
        description:
            "As a teacher of kids and adults, I have seen that students learn the best when having fun. My materials explore Korean through age-appropriate, entertaining subjects.",
    },
    {
        _id: 2,
        title: "Practical Language",
        description:
            "Officia id occaecat qui ea qui nisi occaecat id commodo irure est nostrud reprehenderit mollit. Veniam exercitation magna quis eu anim ea reprehenderit enim veniam.",
    },
    {
        _id: 3,
        title: "Accuracy",
        description:
            "Mollit duis fugiat tempor laboris pariatur sint cillum. Excepteur culpa minim qui ad pariatur id qui eu. Proident duis minim cupidatat est aliquip eu duis do nostrud laborum commodo sit.",
    },
];

export const customerTypesData = [
    {
        _id: 1,
        name: "Language Learners",
        image: learnerSVG,
        msg: "I still struggle with verb endings after 3 years of learning.",
        subMsg: "Our materials will train your brain to grab the correct ending for the context of the sentence.",
        link: "/about",
    },
    {
        _id: 2,
        name: "Parents",
        image: parentsSVG,
        msg: "It’s hard to get my kids excited about learning Korean with boring materials.",
        subMsg: "Our materials are interactive and thought-provoking, improving retention of the subject.",
        link: "/about",
    },
    {
        _id: 3,
        name: "Korean Teachers",
        image: teacherSVG,
        msg: "I want to give my students practice exercises, but I don't have enough time to make them.",
        subMsg: "Our materials are loaded with exercises for each grammar point and each exercise includes an explanation of the context.",
        link: "/about",
    },
];

// Quill Editor Settings 1
export const editorModules = {
    toolbar: [
        [{ header: [1, 2, 3, 4, 5, 6, false] }],
        ["bold", "italic", "underline", "strike", "blockquote"],
        [
            { list: "ordered" },
            { list: "bullet" },
            { indent: "-1" },
            { indent: "+1" },
        ],
        ["link", "image"],
        ["clean"],
    ],
};

// Quill Editor Settings 2
export const editorFormats = [
    "header",
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "list",
    "bullet",
    "indent",
    "link",
    "image",
];

export const countryList = [
    "United States",
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Indian Ocean Territory",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Caribbean Netherlands",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "DR Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern and Antarctic Lands",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Réunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé and Príncipe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States Minor Outlying Islands",
    "Uruguay",
    "U.S. Virgin Islands",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export const usStatesList = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
];
